# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/roman/Projects/plot-cv/quickjs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/roman/Projects/plot-cv/quickjs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roman/Projects/plot-cv/quickjs/CMakeFiles /home/roman/Projects/plot-cv/quickjs/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roman/Projects/plot-cv/quickjs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named .ctags

# Build rule for target.
.ctags: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 .ctags
.PHONY : .ctags

# fast build rule for target.
.ctags/fast:
	$(MAKE) -f CMakeFiles/.ctags.dir/build.make CMakeFiles/.ctags.dir/build
.PHONY : .ctags/fast

#=============================================================================
# Target rules for targets named qjsc

# Build rule for target.
qjsc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjsc
.PHONY : qjsc

# fast build rule for target.
qjsc/fast:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/build
.PHONY : qjsc/fast

#=============================================================================
# Target rules for targets named quickjs

# Build rule for target.
quickjs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 quickjs
.PHONY : quickjs

# fast build rule for target.
quickjs/fast:
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/build
.PHONY : quickjs/fast

#=============================================================================
# Target rules for targets named qjs

# Build rule for target.
qjs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs
.PHONY : qjs

# fast build rule for target.
qjs/fast:
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/build
.PHONY : qjs/fast

#=============================================================================
# Target rules for targets named quickjs-static

# Build rule for target.
quickjs-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 quickjs-static
.PHONY : quickjs-static

# fast build rule for target.
quickjs-static/fast:
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/build
.PHONY : quickjs-static/fast

#=============================================================================
# Target rules for targets named hello.c

# Build rule for target.
hello.c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello.c
.PHONY : hello.c

# fast build rule for target.
hello.c/fast:
	$(MAKE) -f CMakeFiles/hello.c.dir/build.make CMakeFiles/hello.c.dir/build
.PHONY : hello.c/fast

#=============================================================================
# Target rules for targets named qjs-glfw

# Build rule for target.
qjs-glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-glfw
.PHONY : qjs-glfw

# fast build rule for target.
qjs-glfw/fast:
	$(MAKE) -f qjs-glfw/CMakeFiles/qjs-glfw.dir/build.make qjs-glfw/CMakeFiles/qjs-glfw.dir/build
.PHONY : qjs-glfw/fast

#=============================================================================
# Target rules for targets named qjs-nanovg

# Build rule for target.
qjs-nanovg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-nanovg
.PHONY : qjs-nanovg

# fast build rule for target.
qjs-nanovg/fast:
	$(MAKE) -f qjs-nanovg/CMakeFiles/qjs-nanovg.dir/build.make qjs-nanovg/CMakeFiles/qjs-nanovg.dir/build
.PHONY : qjs-nanovg/fast

#=============================================================================
# Target rules for targets named qjs-imgui-static

# Build rule for target.
qjs-imgui-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-imgui-static
.PHONY : qjs-imgui-static

# fast build rule for target.
qjs-imgui-static/fast:
	$(MAKE) -f qjs-imgui/CMakeFiles/qjs-imgui-static.dir/build.make qjs-imgui/CMakeFiles/qjs-imgui-static.dir/build
.PHONY : qjs-imgui-static/fast

#=============================================================================
# Target rules for targets named qjs-imgui

# Build rule for target.
qjs-imgui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-imgui
.PHONY : qjs-imgui

# fast build rule for target.
qjs-imgui/fast:
	$(MAKE) -f qjs-imgui/CMakeFiles/qjs-imgui.dir/build.make qjs-imgui/CMakeFiles/qjs-imgui.dir/build
.PHONY : qjs-imgui/fast

#=============================================================================
# Target rules for targets named imgui_demo

# Build rule for target.
imgui_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imgui_demo
.PHONY : imgui_demo

# fast build rule for target.
imgui_demo/fast:
	$(MAKE) -f qjs-imgui/CMakeFiles/imgui_demo.dir/build.make qjs-imgui/CMakeFiles/imgui_demo.dir/build
.PHONY : imgui_demo/fast

#=============================================================================
# Target rules for targets named quickjs-ffi

# Build rule for target.
quickjs-ffi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 quickjs-ffi
.PHONY : quickjs-ffi

# fast build rule for target.
quickjs-ffi/fast:
	$(MAKE) -f qjs-ffi/CMakeFiles/quickjs-ffi.dir/build.make qjs-ffi/CMakeFiles/quickjs-ffi.dir/build
.PHONY : quickjs-ffi/fast

#=============================================================================
# Target rules for targets named do_tests

# Build rule for target.
do_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 do_tests
.PHONY : do_tests

# fast build rule for target.
do_tests/fast:
	$(MAKE) -f qjs-net/CMakeFiles/do_tests.dir/build.make qjs-net/CMakeFiles/do_tests.dir/build
.PHONY : do_tests/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f qjs-net/CMakeFiles/NightlyMemCheck.dir/build.make qjs-net/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f qjs-net/CMakeFiles/NightlyTest.dir/build.make qjs-net/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f qjs-net/CMakeFiles/ContinuousConfigure.dir/build.make qjs-net/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f qjs-net/CMakeFiles/ContinuousBuild.dir/build.make qjs-net/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f qjs-net/CMakeFiles/NightlyConfigure.dir/build.make qjs-net/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f qjs-net/CMakeFiles/NightlyMemoryCheck.dir/build.make qjs-net/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f qjs-net/CMakeFiles/ContinuousUpdate.dir/build.make qjs-net/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f qjs-net/CMakeFiles/NightlyUpdate.dir/build.make qjs-net/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f qjs-net/CMakeFiles/ExperimentalMemCheck.dir/build.make qjs-net/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f qjs-net/CMakeFiles/ExperimentalSubmit.dir/build.make qjs-net/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f qjs-net/CMakeFiles/Experimental.dir/build.make qjs-net/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f qjs-net/CMakeFiles/ContinuousCoverage.dir/build.make qjs-net/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f qjs-net/CMakeFiles/ExperimentalConfigure.dir/build.make qjs-net/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f qjs-net/CMakeFiles/Continuous.dir/build.make qjs-net/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f qjs-net/CMakeFiles/Nightly.dir/build.make qjs-net/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f qjs-net/CMakeFiles/NightlySubmit.dir/build.make qjs-net/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f qjs-net/CMakeFiles/NightlyStart.dir/build.make qjs-net/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f qjs-net/CMakeFiles/ExperimentalCoverage.dir/build.make qjs-net/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f qjs-net/CMakeFiles/NightlyCoverage.dir/build.make qjs-net/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f qjs-net/CMakeFiles/ExperimentalTest.dir/build.make qjs-net/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named quickjs-minnet

# Build rule for target.
quickjs-minnet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 quickjs-minnet
.PHONY : quickjs-minnet

# fast build rule for target.
quickjs-minnet/fast:
	$(MAKE) -f qjs-net/CMakeFiles/quickjs-minnet.dir/build.make qjs-net/CMakeFiles/quickjs-minnet.dir/build
.PHONY : quickjs-minnet/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f qjs-net/CMakeFiles/ExperimentalStart.dir/build.make qjs-net/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f qjs-net/CMakeFiles/NightlyBuild.dir/build.make qjs-net/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f qjs-net/CMakeFiles/ExperimentalBuild.dir/build.make qjs-net/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f qjs-net/CMakeFiles/ExperimentalUpdate.dir/build.make qjs-net/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f qjs-net/CMakeFiles/ContinuousStart.dir/build.make qjs-net/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f qjs-net/CMakeFiles/ContinuousMemCheck.dir/build.make qjs-net/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f qjs-net/CMakeFiles/ContinuousTest.dir/build.make qjs-net/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f qjs-net/CMakeFiles/ContinuousSubmit.dir/build.make qjs-net/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named qjs-lexer-static

# Build rule for target.
qjs-lexer-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-lexer-static
.PHONY : qjs-lexer-static

# fast build rule for target.
qjs-lexer-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-lexer-static.dir/build.make qjs-modules/CMakeFiles/qjs-lexer-static.dir/build
.PHONY : qjs-lexer-static/fast

#=============================================================================
# Target rules for targets named qjs-syscallerror

# Build rule for target.
qjs-syscallerror: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-syscallerror
.PHONY : qjs-syscallerror

# fast build rule for target.
qjs-syscallerror/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-syscallerror.dir/build.make qjs-modules/CMakeFiles/qjs-syscallerror.dir/build
.PHONY : qjs-syscallerror/fast

#=============================================================================
# Target rules for targets named qjs-repeater-static

# Build rule for target.
qjs-repeater-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-repeater-static
.PHONY : qjs-repeater-static

# fast build rule for target.
qjs-repeater-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-repeater-static.dir/build.make qjs-modules/CMakeFiles/qjs-repeater-static.dir/build
.PHONY : qjs-repeater-static/fast

#=============================================================================
# Target rules for targets named qjs-archive-static

# Build rule for target.
qjs-archive-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-archive-static
.PHONY : qjs-archive-static

# fast build rule for target.
qjs-archive-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-archive-static.dir/build.make qjs-modules/CMakeFiles/qjs-archive-static.dir/build
.PHONY : qjs-archive-static/fast

#=============================================================================
# Target rules for targets named qjs-pointer-static

# Build rule for target.
qjs-pointer-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-pointer-static
.PHONY : qjs-pointer-static

# fast build rule for target.
qjs-pointer-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-pointer-static.dir/build.make qjs-modules/CMakeFiles/qjs-pointer-static.dir/build
.PHONY : qjs-pointer-static/fast

#=============================================================================
# Target rules for targets named qjs-textcode-static

# Build rule for target.
qjs-textcode-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-textcode-static
.PHONY : qjs-textcode-static

# fast build rule for target.
qjs-textcode-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-textcode-static.dir/build.make qjs-modules/CMakeFiles/qjs-textcode-static.dir/build
.PHONY : qjs-textcode-static/fast

#=============================================================================
# Target rules for targets named console.c

# Build rule for target.
console.c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 console.c
.PHONY : console.c

# fast build rule for target.
console.c/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/console.c.dir/build.make qjs-modules/CMakeFiles/console.c.dir/build
.PHONY : console.c/fast

#=============================================================================
# Target rules for targets named events.c

# Build rule for target.
events.c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 events.c
.PHONY : events.c

# fast build rule for target.
events.c/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/events.c.dir/build.make qjs-modules/CMakeFiles/events.c.dir/build
.PHONY : events.c/fast

#=============================================================================
# Target rules for targets named qjs-tree-walker-static

# Build rule for target.
qjs-tree-walker-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-tree-walker-static
.PHONY : qjs-tree-walker-static

# fast build rule for target.
qjs-tree-walker-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-tree-walker-static.dir/build.make qjs-modules/CMakeFiles/qjs-tree-walker-static.dir/build
.PHONY : qjs-tree-walker-static/fast

#=============================================================================
# Target rules for targets named qjs-pointer

# Build rule for target.
qjs-pointer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-pointer
.PHONY : qjs-pointer

# fast build rule for target.
qjs-pointer/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-pointer.dir/build.make qjs-modules/CMakeFiles/qjs-pointer.dir/build
.PHONY : qjs-pointer/fast

#=============================================================================
# Target rules for targets named qjs-misc-static

# Build rule for target.
qjs-misc-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-misc-static
.PHONY : qjs-misc-static

# fast build rule for target.
qjs-misc-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-misc-static.dir/build.make qjs-modules/CMakeFiles/qjs-misc-static.dir/build
.PHONY : qjs-misc-static/fast

#=============================================================================
# Target rules for targets named qjs-gpio-static

# Build rule for target.
qjs-gpio-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-gpio-static
.PHONY : qjs-gpio-static

# fast build rule for target.
qjs-gpio-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-gpio-static.dir/build.make qjs-modules/CMakeFiles/qjs-gpio-static.dir/build
.PHONY : qjs-gpio-static/fast

#=============================================================================
# Target rules for targets named qjs-path-static

# Build rule for target.
qjs-path-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-path-static
.PHONY : qjs-path-static

# fast build rule for target.
qjs-path-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-path-static.dir/build.make qjs-modules/CMakeFiles/qjs-path-static.dir/build
.PHONY : qjs-path-static/fast

#=============================================================================
# Target rules for targets named qjs-archive

# Build rule for target.
qjs-archive: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-archive
.PHONY : qjs-archive

# fast build rule for target.
qjs-archive/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-archive.dir/build.make qjs-modules/CMakeFiles/qjs-archive.dir/build
.PHONY : qjs-archive/fast

#=============================================================================
# Target rules for targets named qjs-sockets

# Build rule for target.
qjs-sockets: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-sockets
.PHONY : qjs-sockets

# fast build rule for target.
qjs-sockets/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-sockets.dir/build.make qjs-modules/CMakeFiles/qjs-sockets.dir/build
.PHONY : qjs-sockets/fast

#=============================================================================
# Target rules for targets named qjs-stream

# Build rule for target.
qjs-stream: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-stream
.PHONY : qjs-stream

# fast build rule for target.
qjs-stream/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-stream.dir/build.make qjs-modules/CMakeFiles/qjs-stream.dir/build
.PHONY : qjs-stream/fast

#=============================================================================
# Target rules for targets named qjs-deep-static

# Build rule for target.
qjs-deep-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-deep-static
.PHONY : qjs-deep-static

# fast build rule for target.
qjs-deep-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-deep-static.dir/build.make qjs-modules/CMakeFiles/qjs-deep-static.dir/build
.PHONY : qjs-deep-static/fast

#=============================================================================
# Target rules for targets named qjs-bjson

# Build rule for target.
qjs-bjson: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-bjson
.PHONY : qjs-bjson

# fast build rule for target.
qjs-bjson/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-bjson.dir/build.make qjs-modules/CMakeFiles/qjs-bjson.dir/build
.PHONY : qjs-bjson/fast

#=============================================================================
# Target rules for targets named repl.c

# Build rule for target.
repl.c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 repl.c
.PHONY : repl.c

# fast build rule for target.
repl.c/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/repl.c.dir/build.make qjs-modules/CMakeFiles/repl.c.dir/build
.PHONY : repl.c/fast

#=============================================================================
# Target rules for targets named qjs-lexer

# Build rule for target.
qjs-lexer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-lexer
.PHONY : qjs-lexer

# fast build rule for target.
qjs-lexer/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-lexer.dir/build.make qjs-modules/CMakeFiles/qjs-lexer.dir/build
.PHONY : qjs-lexer/fast

#=============================================================================
# Target rules for targets named qjs-predicate-static

# Build rule for target.
qjs-predicate-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-predicate-static
.PHONY : qjs-predicate-static

# fast build rule for target.
qjs-predicate-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-predicate-static.dir/build.make qjs-modules/CMakeFiles/qjs-predicate-static.dir/build
.PHONY : qjs-predicate-static/fast

#=============================================================================
# Target rules for targets named qjs-tree-walker

# Build rule for target.
qjs-tree-walker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-tree-walker
.PHONY : qjs-tree-walker

# fast build rule for target.
qjs-tree-walker/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-tree-walker.dir/build.make qjs-modules/CMakeFiles/qjs-tree-walker.dir/build
.PHONY : qjs-tree-walker/fast

#=============================================================================
# Target rules for targets named qjs-path

# Build rule for target.
qjs-path: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-path
.PHONY : qjs-path

# fast build rule for target.
qjs-path/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-path.dir/build.make qjs-modules/CMakeFiles/qjs-path.dir/build
.PHONY : qjs-path/fast

#=============================================================================
# Target rules for targets named qjs-location

# Build rule for target.
qjs-location: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-location
.PHONY : qjs-location

# fast build rule for target.
qjs-location/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-location.dir/build.make qjs-modules/CMakeFiles/qjs-location.dir/build
.PHONY : qjs-location/fast

#=============================================================================
# Target rules for targets named qjs-misc

# Build rule for target.
qjs-misc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-misc
.PHONY : qjs-misc

# fast build rule for target.
qjs-misc/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-misc.dir/build.make qjs-modules/CMakeFiles/qjs-misc.dir/build
.PHONY : qjs-misc/fast

#=============================================================================
# Target rules for targets named qjs-bjson-static

# Build rule for target.
qjs-bjson-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-bjson-static
.PHONY : qjs-bjson-static

# fast build rule for target.
qjs-bjson-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-bjson-static.dir/build.make qjs-modules/CMakeFiles/qjs-bjson-static.dir/build
.PHONY : qjs-bjson-static/fast

#=============================================================================
# Target rules for targets named qjs-stream-static

# Build rule for target.
qjs-stream-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-stream-static
.PHONY : qjs-stream-static

# fast build rule for target.
qjs-stream-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-stream-static.dir/build.make qjs-modules/CMakeFiles/qjs-stream-static.dir/build
.PHONY : qjs-stream-static/fast

#=============================================================================
# Target rules for targets named qjs-sockets-static

# Build rule for target.
qjs-sockets-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-sockets-static
.PHONY : qjs-sockets-static

# fast build rule for target.
qjs-sockets-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-sockets-static.dir/build.make qjs-modules/CMakeFiles/qjs-sockets-static.dir/build
.PHONY : qjs-sockets-static/fast

#=============================================================================
# Target rules for targets named qjs-deep

# Build rule for target.
qjs-deep: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-deep
.PHONY : qjs-deep

# fast build rule for target.
qjs-deep/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-deep.dir/build.make qjs-modules/CMakeFiles/qjs-deep.dir/build
.PHONY : qjs-deep/fast

#=============================================================================
# Target rules for targets named qjs-xml

# Build rule for target.
qjs-xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-xml
.PHONY : qjs-xml

# fast build rule for target.
qjs-xml/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-xml.dir/build.make qjs-modules/CMakeFiles/qjs-xml.dir/build
.PHONY : qjs-xml/fast

#=============================================================================
# Target rules for targets named qjs-location-static

# Build rule for target.
qjs-location-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-location-static
.PHONY : qjs-location-static

# fast build rule for target.
qjs-location-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-location-static.dir/build.make qjs-modules/CMakeFiles/qjs-location-static.dir/build
.PHONY : qjs-location-static/fast

#=============================================================================
# Target rules for targets named perf_hooks.c

# Build rule for target.
perf_hooks.c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 perf_hooks.c
.PHONY : perf_hooks.c

# fast build rule for target.
perf_hooks.c/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/perf_hooks.c.dir/build.make qjs-modules/CMakeFiles/perf_hooks.c.dir/build
.PHONY : perf_hooks.c/fast

#=============================================================================
# Target rules for targets named qjs-syscallerror-static

# Build rule for target.
qjs-syscallerror-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-syscallerror-static
.PHONY : qjs-syscallerror-static

# fast build rule for target.
qjs-syscallerror-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-syscallerror-static.dir/build.make qjs-modules/CMakeFiles/qjs-syscallerror-static.dir/build
.PHONY : qjs-syscallerror-static/fast

#=============================================================================
# Target rules for targets named qjsm

# Build rule for target.
qjsm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjsm
.PHONY : qjsm

# fast build rule for target.
qjsm/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjsm.dir/build.make qjs-modules/CMakeFiles/qjsm.dir/build
.PHONY : qjsm/fast

#=============================================================================
# Target rules for targets named qjs-inspect-static

# Build rule for target.
qjs-inspect-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-inspect-static
.PHONY : qjs-inspect-static

# fast build rule for target.
qjs-inspect-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-inspect-static.dir/build.make qjs-modules/CMakeFiles/qjs-inspect-static.dir/build
.PHONY : qjs-inspect-static/fast

#=============================================================================
# Target rules for targets named qjs-mmap

# Build rule for target.
qjs-mmap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-mmap
.PHONY : qjs-mmap

# fast build rule for target.
qjs-mmap/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-mmap.dir/build.make qjs-modules/CMakeFiles/qjs-mmap.dir/build
.PHONY : qjs-mmap/fast

#=============================================================================
# Target rules for targets named csv.c

# Build rule for target.
csv.c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csv.c
.PHONY : csv.c

# fast build rule for target.
csv.c/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/csv.c.dir/build.make qjs-modules/CMakeFiles/csv.c.dir/build
.PHONY : csv.c/fast

#=============================================================================
# Target rules for targets named qjs-predicate

# Build rule for target.
qjs-predicate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-predicate
.PHONY : qjs-predicate

# fast build rule for target.
qjs-predicate/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-predicate.dir/build.make qjs-modules/CMakeFiles/qjs-predicate.dir/build
.PHONY : qjs-predicate/fast

#=============================================================================
# Target rules for targets named qjs-xml-static

# Build rule for target.
qjs-xml-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-xml-static
.PHONY : qjs-xml-static

# fast build rule for target.
qjs-xml-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-xml-static.dir/build.make qjs-modules/CMakeFiles/qjs-xml-static.dir/build
.PHONY : qjs-xml-static/fast

#=============================================================================
# Target rules for targets named qjs-child-process

# Build rule for target.
qjs-child-process: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-child-process
.PHONY : qjs-child-process

# fast build rule for target.
qjs-child-process/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-child-process.dir/build.make qjs-modules/CMakeFiles/qjs-child-process.dir/build
.PHONY : qjs-child-process/fast

#=============================================================================
# Target rules for targets named qjs-textcode

# Build rule for target.
qjs-textcode: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-textcode
.PHONY : qjs-textcode

# fast build rule for target.
qjs-textcode/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-textcode.dir/build.make qjs-modules/CMakeFiles/qjs-textcode.dir/build
.PHONY : qjs-textcode/fast

#=============================================================================
# Target rules for targets named qjs-child-process-static

# Build rule for target.
qjs-child-process-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-child-process-static
.PHONY : qjs-child-process-static

# fast build rule for target.
qjs-child-process-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-child-process-static.dir/build.make qjs-modules/CMakeFiles/qjs-child-process-static.dir/build
.PHONY : qjs-child-process-static/fast

#=============================================================================
# Target rules for targets named qjs-blob-static

# Build rule for target.
qjs-blob-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-blob-static
.PHONY : qjs-blob-static

# fast build rule for target.
qjs-blob-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-blob-static.dir/build.make qjs-modules/CMakeFiles/qjs-blob-static.dir/build
.PHONY : qjs-blob-static/fast

#=============================================================================
# Target rules for targets named qjs-gpio

# Build rule for target.
qjs-gpio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-gpio
.PHONY : qjs-gpio

# fast build rule for target.
qjs-gpio/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-gpio.dir/build.make qjs-modules/CMakeFiles/qjs-gpio.dir/build
.PHONY : qjs-gpio/fast

#=============================================================================
# Target rules for targets named qjs-mmap-static

# Build rule for target.
qjs-mmap-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-mmap-static
.PHONY : qjs-mmap-static

# fast build rule for target.
qjs-mmap-static/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-mmap-static.dir/build.make qjs-modules/CMakeFiles/qjs-mmap-static.dir/build
.PHONY : qjs-mmap-static/fast

#=============================================================================
# Target rules for targets named fs.c

# Build rule for target.
fs.c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fs.c
.PHONY : fs.c

# fast build rule for target.
fs.c/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/fs.c.dir/build.make qjs-modules/CMakeFiles/fs.c.dir/build
.PHONY : fs.c/fast

#=============================================================================
# Target rules for targets named ecmascript.c

# Build rule for target.
ecmascript.c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ecmascript.c
.PHONY : ecmascript.c

# fast build rule for target.
ecmascript.c/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/ecmascript.c.dir/build.make qjs-modules/CMakeFiles/ecmascript.c.dir/build
.PHONY : ecmascript.c/fast

#=============================================================================
# Target rules for targets named qjs-blob

# Build rule for target.
qjs-blob: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-blob
.PHONY : qjs-blob

# fast build rule for target.
qjs-blob/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-blob.dir/build.make qjs-modules/CMakeFiles/qjs-blob.dir/build
.PHONY : qjs-blob/fast

#=============================================================================
# Target rules for targets named qjs-inspect

# Build rule for target.
qjs-inspect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-inspect
.PHONY : qjs-inspect

# fast build rule for target.
qjs-inspect/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-inspect.dir/build.make qjs-modules/CMakeFiles/qjs-inspect.dir/build
.PHONY : qjs-inspect/fast

#=============================================================================
# Target rules for targets named process.c

# Build rule for target.
process.c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 process.c
.PHONY : process.c

# fast build rule for target.
process.c/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/process.c.dir/build.make qjs-modules/CMakeFiles/process.c.dir/build
.PHONY : process.c/fast

#=============================================================================
# Target rules for targets named require.c

# Build rule for target.
require.c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 require.c
.PHONY : require.c

# fast build rule for target.
require.c/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/require.c.dir/build.make qjs-modules/CMakeFiles/require.c.dir/build
.PHONY : require.c/fast

#=============================================================================
# Target rules for targets named stack.c

# Build rule for target.
stack.c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stack.c
.PHONY : stack.c

# fast build rule for target.
stack.c/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/stack.c.dir/build.make qjs-modules/CMakeFiles/stack.c.dir/build
.PHONY : stack.c/fast

#=============================================================================
# Target rules for targets named qjs-repeater

# Build rule for target.
qjs-repeater: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qjs-repeater
.PHONY : qjs-repeater

# fast build rule for target.
qjs-repeater/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/qjs-repeater.dir/build.make qjs-modules/CMakeFiles/qjs-repeater.dir/build
.PHONY : qjs-repeater/fast

#=============================================================================
# Target rules for targets named tty.c

# Build rule for target.
tty.c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tty.c
.PHONY : tty.c

# fast build rule for target.
tty.c/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/tty.c.dir/build.make qjs-modules/CMakeFiles/tty.c.dir/build
.PHONY : tty.c/fast

#=============================================================================
# Target rules for targets named parser.c

# Build rule for target.
parser.c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parser.c
.PHONY : parser.c

# fast build rule for target.
parser.c/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/parser.c.dir/build.make qjs-modules/CMakeFiles/parser.c.dir/build
.PHONY : parser.c/fast

#=============================================================================
# Target rules for targets named util.c

# Build rule for target.
util.c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util.c
.PHONY : util.c

# fast build rule for target.
util.c/fast:
	$(MAKE) -f qjs-modules/CMakeFiles/util.c.dir/build.make qjs-modules/CMakeFiles/util.c.dir/build
.PHONY : util.c/fast

cutils.o: cutils.c.o

.PHONY : cutils.o

# target to build an object file
cutils.c.o:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/cutils.c.o
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/cutils.c.o
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/cutils.c.o
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/cutils.c.o
.PHONY : cutils.c.o

cutils.i: cutils.c.i

.PHONY : cutils.i

# target to preprocess a source file
cutils.c.i:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/cutils.c.i
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/cutils.c.i
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/cutils.c.i
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/cutils.c.i
.PHONY : cutils.c.i

cutils.s: cutils.c.s

.PHONY : cutils.s

# target to generate assembly for a file
cutils.c.s:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/cutils.c.s
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/cutils.c.s
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/cutils.c.s
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/cutils.c.s
.PHONY : cutils.c.s

libbf.o: libbf.c.o

.PHONY : libbf.o

# target to build an object file
libbf.c.o:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/libbf.c.o
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/libbf.c.o
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/libbf.c.o
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/libbf.c.o
.PHONY : libbf.c.o

libbf.i: libbf.c.i

.PHONY : libbf.i

# target to preprocess a source file
libbf.c.i:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/libbf.c.i
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/libbf.c.i
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/libbf.c.i
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/libbf.c.i
.PHONY : libbf.c.i

libbf.s: libbf.c.s

.PHONY : libbf.s

# target to generate assembly for a file
libbf.c.s:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/libbf.c.s
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/libbf.c.s
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/libbf.c.s
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/libbf.c.s
.PHONY : libbf.c.s

libregexp.o: libregexp.c.o

.PHONY : libregexp.o

# target to build an object file
libregexp.c.o:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/libregexp.c.o
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/libregexp.c.o
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/libregexp.c.o
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/libregexp.c.o
.PHONY : libregexp.c.o

libregexp.i: libregexp.c.i

.PHONY : libregexp.i

# target to preprocess a source file
libregexp.c.i:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/libregexp.c.i
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/libregexp.c.i
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/libregexp.c.i
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/libregexp.c.i
.PHONY : libregexp.c.i

libregexp.s: libregexp.c.s

.PHONY : libregexp.s

# target to generate assembly for a file
libregexp.c.s:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/libregexp.c.s
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/libregexp.c.s
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/libregexp.c.s
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/libregexp.c.s
.PHONY : libregexp.c.s

libunicode.o: libunicode.c.o

.PHONY : libunicode.o

# target to build an object file
libunicode.c.o:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/libunicode.c.o
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/libunicode.c.o
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/libunicode.c.o
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/libunicode.c.o
.PHONY : libunicode.c.o

libunicode.i: libunicode.c.i

.PHONY : libunicode.i

# target to preprocess a source file
libunicode.c.i:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/libunicode.c.i
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/libunicode.c.i
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/libunicode.c.i
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/libunicode.c.i
.PHONY : libunicode.c.i

libunicode.s: libunicode.c.s

.PHONY : libunicode.s

# target to generate assembly for a file
libunicode.c.s:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/libunicode.c.s
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/libunicode.c.s
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/libunicode.c.s
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/libunicode.c.s
.PHONY : libunicode.c.s

qjs.o: qjs.c.o

.PHONY : qjs.o

# target to build an object file
qjs.c.o:
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/qjs.c.o
.PHONY : qjs.c.o

qjs.i: qjs.c.i

.PHONY : qjs.i

# target to preprocess a source file
qjs.c.i:
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/qjs.c.i
.PHONY : qjs.c.i

qjs.s: qjs.c.s

.PHONY : qjs.s

# target to generate assembly for a file
qjs.c.s:
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/qjs.c.s
.PHONY : qjs.c.s

qjsc.o: qjsc.c.o

.PHONY : qjsc.o

# target to build an object file
qjsc.c.o:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/qjsc.c.o
.PHONY : qjsc.c.o

qjsc.i: qjsc.c.i

.PHONY : qjsc.i

# target to preprocess a source file
qjsc.c.i:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/qjsc.c.i
.PHONY : qjsc.c.i

qjsc.s: qjsc.c.s

.PHONY : qjsc.s

# target to generate assembly for a file
qjsc.c.s:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/qjsc.c.s
.PHONY : qjsc.c.s

qjscalc.o: qjscalc.c.o

.PHONY : qjscalc.o

# target to build an object file
qjscalc.c.o:
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/qjscalc.c.o
.PHONY : qjscalc.c.o

qjscalc.i: qjscalc.c.i

.PHONY : qjscalc.i

# target to preprocess a source file
qjscalc.c.i:
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/qjscalc.c.i
.PHONY : qjscalc.c.i

qjscalc.s: qjscalc.c.s

.PHONY : qjscalc.s

# target to generate assembly for a file
qjscalc.c.s:
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/qjscalc.c.s
.PHONY : qjscalc.c.s

quickjs-debugger-transport-unix.o: quickjs-debugger-transport-unix.c.o

.PHONY : quickjs-debugger-transport-unix.o

# target to build an object file
quickjs-debugger-transport-unix.c.o:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/quickjs-debugger-transport-unix.c.o
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/quickjs-debugger-transport-unix.c.o
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/quickjs-debugger-transport-unix.c.o
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/quickjs-debugger-transport-unix.c.o
.PHONY : quickjs-debugger-transport-unix.c.o

quickjs-debugger-transport-unix.i: quickjs-debugger-transport-unix.c.i

.PHONY : quickjs-debugger-transport-unix.i

# target to preprocess a source file
quickjs-debugger-transport-unix.c.i:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/quickjs-debugger-transport-unix.c.i
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/quickjs-debugger-transport-unix.c.i
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/quickjs-debugger-transport-unix.c.i
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/quickjs-debugger-transport-unix.c.i
.PHONY : quickjs-debugger-transport-unix.c.i

quickjs-debugger-transport-unix.s: quickjs-debugger-transport-unix.c.s

.PHONY : quickjs-debugger-transport-unix.s

# target to generate assembly for a file
quickjs-debugger-transport-unix.c.s:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/quickjs-debugger-transport-unix.c.s
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/quickjs-debugger-transport-unix.c.s
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/quickjs-debugger-transport-unix.c.s
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/quickjs-debugger-transport-unix.c.s
.PHONY : quickjs-debugger-transport-unix.c.s

quickjs-debugger.o: quickjs-debugger.c.o

.PHONY : quickjs-debugger.o

# target to build an object file
quickjs-debugger.c.o:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/quickjs-debugger.c.o
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/quickjs-debugger.c.o
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/quickjs-debugger.c.o
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/quickjs-debugger.c.o
.PHONY : quickjs-debugger.c.o

quickjs-debugger.i: quickjs-debugger.c.i

.PHONY : quickjs-debugger.i

# target to preprocess a source file
quickjs-debugger.c.i:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/quickjs-debugger.c.i
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/quickjs-debugger.c.i
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/quickjs-debugger.c.i
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/quickjs-debugger.c.i
.PHONY : quickjs-debugger.c.i

quickjs-debugger.s: quickjs-debugger.c.s

.PHONY : quickjs-debugger.s

# target to generate assembly for a file
quickjs-debugger.c.s:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/quickjs-debugger.c.s
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/quickjs-debugger.c.s
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/quickjs-debugger.c.s
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/quickjs-debugger.c.s
.PHONY : quickjs-debugger.c.s

quickjs-find-module.o: quickjs-find-module.c.o

.PHONY : quickjs-find-module.o

# target to build an object file
quickjs-find-module.c.o:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/quickjs-find-module.c.o
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/quickjs-find-module.c.o
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/quickjs-find-module.c.o
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/quickjs-find-module.c.o
.PHONY : quickjs-find-module.c.o

quickjs-find-module.i: quickjs-find-module.c.i

.PHONY : quickjs-find-module.i

# target to preprocess a source file
quickjs-find-module.c.i:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/quickjs-find-module.c.i
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/quickjs-find-module.c.i
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/quickjs-find-module.c.i
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/quickjs-find-module.c.i
.PHONY : quickjs-find-module.c.i

quickjs-find-module.s: quickjs-find-module.c.s

.PHONY : quickjs-find-module.s

# target to generate assembly for a file
quickjs-find-module.c.s:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/quickjs-find-module.c.s
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/quickjs-find-module.c.s
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/quickjs-find-module.c.s
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/quickjs-find-module.c.s
.PHONY : quickjs-find-module.c.s

quickjs-libc.o: quickjs-libc.c.o

.PHONY : quickjs-libc.o

# target to build an object file
quickjs-libc.c.o:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/quickjs-libc.c.o
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/quickjs-libc.c.o
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/quickjs-libc.c.o
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/quickjs-libc.c.o
.PHONY : quickjs-libc.c.o

quickjs-libc.i: quickjs-libc.c.i

.PHONY : quickjs-libc.i

# target to preprocess a source file
quickjs-libc.c.i:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/quickjs-libc.c.i
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/quickjs-libc.c.i
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/quickjs-libc.c.i
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/quickjs-libc.c.i
.PHONY : quickjs-libc.c.i

quickjs-libc.s: quickjs-libc.c.s

.PHONY : quickjs-libc.s

# target to generate assembly for a file
quickjs-libc.c.s:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/quickjs-libc.c.s
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/quickjs-libc.c.s
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/quickjs-libc.c.s
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/quickjs-libc.c.s
.PHONY : quickjs-libc.c.s

quickjs.o: quickjs.c.o

.PHONY : quickjs.o

# target to build an object file
quickjs.c.o:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/quickjs.c.o
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/quickjs.c.o
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/quickjs.c.o
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/quickjs.c.o
.PHONY : quickjs.c.o

quickjs.i: quickjs.c.i

.PHONY : quickjs.i

# target to preprocess a source file
quickjs.c.i:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/quickjs.c.i
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/quickjs.c.i
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/quickjs.c.i
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/quickjs.c.i
.PHONY : quickjs.c.i

quickjs.s: quickjs.c.s

.PHONY : quickjs.s

# target to generate assembly for a file
quickjs.c.s:
	$(MAKE) -f CMakeFiles/qjsc.dir/build.make CMakeFiles/qjsc.dir/quickjs.c.s
	$(MAKE) -f CMakeFiles/quickjs.dir/build.make CMakeFiles/quickjs.dir/quickjs.c.s
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/quickjs.c.s
	$(MAKE) -f CMakeFiles/quickjs-static.dir/build.make CMakeFiles/quickjs-static.dir/quickjs.c.s
.PHONY : quickjs.c.s

repl.o: repl.c.o

.PHONY : repl.o

# target to build an object file
repl.c.o:
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/repl.c.o
.PHONY : repl.c.o

repl.i: repl.c.i

.PHONY : repl.i

# target to preprocess a source file
repl.c.i:
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/repl.c.i
.PHONY : repl.c.i

repl.s: repl.c.s

.PHONY : repl.s

# target to generate assembly for a file
repl.c.s:
	$(MAKE) -f CMakeFiles/qjs.dir/build.make CMakeFiles/qjs.dir/repl.c.s
.PHONY : repl.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... .ctags"
	@echo "... qjsc"
	@echo "... quickjs"
	@echo "... qjs"
	@echo "... quickjs-static"
	@echo "... hello.c"
	@echo "... qjs-glfw"
	@echo "... qjs-nanovg"
	@echo "... qjs-imgui-static"
	@echo "... qjs-imgui"
	@echo "... imgui_demo"
	@echo "... quickjs-ffi"
	@echo "... do_tests"
	@echo "... NightlyMemCheck"
	@echo "... NightlyTest"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyMemoryCheck"
	@echo "... ContinuousUpdate"
	@echo "... NightlyUpdate"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalSubmit"
	@echo "... Experimental"
	@echo "... ContinuousCoverage"
	@echo "... ExperimentalConfigure"
	@echo "... Continuous"
	@echo "... Nightly"
	@echo "... NightlySubmit"
	@echo "... NightlyStart"
	@echo "... ExperimentalCoverage"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalTest"
	@echo "... quickjs-minnet"
	@echo "... ExperimentalStart"
	@echo "... NightlyBuild"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalUpdate"
	@echo "... ContinuousStart"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousTest"
	@echo "... ContinuousSubmit"
	@echo "... qjs-lexer-static"
	@echo "... qjs-syscallerror"
	@echo "... qjs-repeater-static"
	@echo "... qjs-archive-static"
	@echo "... qjs-pointer-static"
	@echo "... qjs-textcode-static"
	@echo "... console.c"
	@echo "... events.c"
	@echo "... qjs-tree-walker-static"
	@echo "... qjs-pointer"
	@echo "... qjs-misc-static"
	@echo "... qjs-gpio-static"
	@echo "... qjs-path-static"
	@echo "... qjs-archive"
	@echo "... qjs-sockets"
	@echo "... qjs-stream"
	@echo "... qjs-deep-static"
	@echo "... qjs-bjson"
	@echo "... repl.c"
	@echo "... qjs-lexer"
	@echo "... qjs-predicate-static"
	@echo "... qjs-tree-walker"
	@echo "... qjs-path"
	@echo "... qjs-location"
	@echo "... qjs-misc"
	@echo "... qjs-bjson-static"
	@echo "... qjs-stream-static"
	@echo "... qjs-sockets-static"
	@echo "... qjs-deep"
	@echo "... qjs-xml"
	@echo "... qjs-location-static"
	@echo "... perf_hooks.c"
	@echo "... qjs-syscallerror-static"
	@echo "... qjsm"
	@echo "... qjs-inspect-static"
	@echo "... qjs-mmap"
	@echo "... csv.c"
	@echo "... qjs-predicate"
	@echo "... qjs-xml-static"
	@echo "... qjs-child-process"
	@echo "... qjs-textcode"
	@echo "... qjs-child-process-static"
	@echo "... qjs-blob-static"
	@echo "... qjs-gpio"
	@echo "... qjs-mmap-static"
	@echo "... fs.c"
	@echo "... ecmascript.c"
	@echo "... qjs-blob"
	@echo "... qjs-inspect"
	@echo "... process.c"
	@echo "... require.c"
	@echo "... stack.c"
	@echo "... qjs-repeater"
	@echo "... tty.c"
	@echo "... parser.c"
	@echo "... util.c"
	@echo "... cutils.o"
	@echo "... cutils.i"
	@echo "... cutils.s"
	@echo "... libbf.o"
	@echo "... libbf.i"
	@echo "... libbf.s"
	@echo "... libregexp.o"
	@echo "... libregexp.i"
	@echo "... libregexp.s"
	@echo "... libunicode.o"
	@echo "... libunicode.i"
	@echo "... libunicode.s"
	@echo "... qjs.o"
	@echo "... qjs.i"
	@echo "... qjs.s"
	@echo "... qjsc.o"
	@echo "... qjsc.i"
	@echo "... qjsc.s"
	@echo "... qjscalc.o"
	@echo "... qjscalc.i"
	@echo "... qjscalc.s"
	@echo "... quickjs-debugger-transport-unix.o"
	@echo "... quickjs-debugger-transport-unix.i"
	@echo "... quickjs-debugger-transport-unix.s"
	@echo "... quickjs-debugger.o"
	@echo "... quickjs-debugger.i"
	@echo "... quickjs-debugger.s"
	@echo "... quickjs-find-module.o"
	@echo "... quickjs-find-module.i"
	@echo "... quickjs-find-module.s"
	@echo "... quickjs-libc.o"
	@echo "... quickjs-libc.i"
	@echo "... quickjs-libc.s"
	@echo "... quickjs.o"
	@echo "... quickjs.i"
	@echo "... quickjs.s"
	@echo "... repl.o"
	@echo "... repl.i"
	@echo "... repl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

